database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  username: test
  password: asdfghjkl
  database: dousheng

redis:
  addr: "127.0.0.1:6379"
  password:
  DB: 0

OSS:
  endPoint: "https://**********.aliyuncs.com"
  accessKey: "************"
  accessSecret: "****************"